// <auto-generated />
using FirstRealASPNETApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstRealASPNETApp.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220125230000_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FirstRealASPNETApp.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            category = "Action",
                            director = "Christopher Nolan",
                            edited = false,
                            rating = "PG-13",
                            title = "The Dark Knight",
                            year = 2008
                        },
                        new
                        {
                            MovieId = 2,
                            category = "Action",
                            director = "Jon Watts",
                            edited = false,
                            rating = "PG-13",
                            title = "Spiderman No Way Home",
                            year = 2021
                        },
                        new
                        {
                            MovieId = 3,
                            category = "Action",
                            director = "Paul Greengrass",
                            edited = false,
                            rating = "PG-13",
                            title = "The Bourne Ultimatum",
                            year = 2007
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
